export const addAuthorUrl = 'https://localhost:7144/api/author/createauthor'
export const getAllAuthorUrl = 'https://localhost:7144/api/author/getallautors'
export const getAuthorUrl = 'https://localhost:7144/api/author/getauthor'
export const updateAuthorUrl = 'https://localhost:7144/api/author/updateauthor'
export const deleteAuthorUrl = 'https://localhost:7144/api/author/deleteauthor'

export const getUserUrl = 'https://localhost:7144/api/user/getuser'
export const getAllUserUrl = 'https://localhost:7144/api/user/getallusers'
export const addUserUrl = 'https://localhost:7144/api/user/createuser'
export const updateUserUrl = 'https://localhost:7144/api/user/updateuser'
export const deleteUserUrl = 'https://localhost:7144/api/user/deleteuser'